services:
  - type: web
    name: samsapp
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn samsapp.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
